/* ---------------------------------------------------------------------
 *                                       _
 *  _ __ ___   __ _ _ __ _ __ ___   ___ | |_
 * | '_ ` _ \ / _` | '__| '_ ` _ \ / _ \| __|
 * | | | | | | (_| | |  | | | | | | (_) | |_
 * |_| |_| |_|\__,_|_|  |_| |_| |_|\___/ \__|
 *
 * Unit of Strength of Materials and Structural Analysis
 * University of Innsbruck,
 * 2020 - today
 *
 * festigkeitslehre@uibk.ac.at
 *
 * This file is part of the MAteRialMOdellingToolbox (marmot).
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * The full text of the license can be found in the file LICENSE.md at
 * the top level directory of marmot.
 * ---------------------------------------------------------------------
 */
#pragma once
#include "Marmot/MarmotElementProperty.h"
#include "Marmot/MarmotExceptions.h"
#include "Marmot/MarmotJournal.h"
#include "Marmot/MarmotMaterialHypoElastic.h"
#include "Marmot/MarmotMaterialHypoElasticFactory.h"
#include "Marmot/MarmotUtils.h"
#include <Eigen/Dense>
#include <algorithm>
#include <array>
#include <cmath>
#include <memory>
#include <numbers>
#include <string>
#include <vector>

namespace Marmot::Elements {

  /**
   * @class Marmot::Elements::BeamFiberSection
   * @brief The integration of a beam cross section over given section points ("fibers"), independent of the shape of
   * the section and of the beam kinematics.
   *
   * @tparam nDim number of spatial dimensions of the beam, 2 or 3
   *
   * The section knows only its points \f$(y_f, z_f, A_f)\f$ (2D: \f$(y_f, A_f)\f$) in the section coordinates of the
   * beam axis, generated by the user or the framework for any shape (EdelweissFE: rectangles, circles, tubes,
   * I-profiles, polygons with holes, explicit point lists). It maps the generalized strains \f$\boldsymbol{e}\f$ (2D:
   * \f$[ \varepsilon_0, \kappa ]\f$, 3D: \f$[ \varepsilon_0, \kappa_y, \kappa_z, \chi ]\f$) to the section forces
   * \f$\boldsymbol{s}\f$ (2D: \f$[ N, M ]\f$, 3D: \f$[ N, M_y, M_z, T ]\f$, work conjugate) and the section tangent.
   * Every point has its own material instance, created by name through the hypoelastic material factory, and its own
   * state. A point has the axial strain \f$\varepsilon_{11} = \varepsilon_0 + z_f \kappa_y - y_f \kappa_z\f$; points
   * off the axis' centroid and non-principal axes (\f$\int y z \mathrm{d}A \neq 0\f$) couple naturally. In 2D the
   * material is evaluated by MarmotMaterialHypoElastic::computeUniaxialStress.
   *
   * Torsion (3D): Saint-Venant torsion without warping, about the centroid \f$(y_c, z_c)\f$ of the points: the points
   * carry the shear strains \f$\gamma_{12} = - s ( z_f - z_c ) \chi\f$, \f$\gamma_{13} = s ( y_f - y_c ) \chi\f$
   * (material evaluated by MarmotMaterialHypoElastic::computeBeamStress, \f$\sigma_{22} = \sigma_{33} = \sigma_{23} =
   * 0\f$), scaled by \f$s = \sqrt{J / \sum_f ( (y_f-y_c)^2 + (z_f-z_c)^2 ) A_f}\f$ such that the elastic torsional
   * stiffness is \f$G J\f$ with the given torsion constant \f$J\f$ (exact for circles and tubes, where \f$s = 1\f$).
   * The shear center offset and warping are neglected; plastic torsion is approximate.
   *
   * Kinematics (small or co-rotated strains) are the business of the beam element: a co-rotational element can use
   * the same section with the generalized strains of its co-rotated frame.
   *
   * State of a point: \f$[ \sigma_{11}, \sigma_{12}, \sigma_{13}, \psi, d, \text{material state} ]\f$.
   */
  template < int nDim >
  class BeamFiberSection {

    static_assert( nDim == 2 || nDim == 3, "BeamFiberSection: nDim must be 2 or 3" );

  public:
    static constexpr int nGeneralized    = nDim == 2 ? 2 : 4;
    static constexpr int nFiberStateVars = 5; ///< fiber stress (3), energy and dissipation density

    using VectorGen = Eigen::Matrix< double, nGeneralized, 1 >;
    using MatrixGen = Eigen::Matrix< double, nGeneralized, nGeneralized >;
    using FiberS    = Eigen::Matrix< double, 3, nGeneralized >; ///< generalized strains -> fiber strains

    /// A section point (fiber)
    struct Fiber {
      double                                       y;    ///< local y coordinate
      double                                       z;    ///< local z coordinate (0 in 2D)
      double                                       area; ///< area (weight)
      FiberS                                       S;    ///< generalized strains -> [eps11, gamma12, gamma13]
      std::unique_ptr< MarmotMaterialHypoElastic > material;
    };

    std::vector< Fiber > fibers;
    double               torsionScaling = 0.0;

    /**
     * Set the section points.
     * @param points 2D: [y_1, A_1, y_2, A_2, ...]; 3D: [y_1, z_1, A_1, ...]
     * @param nPoints the number of points
     * @param J the torsion constant (3D only)
     */
    void setFibers( const double* points, int nPoints, double J = 0.0 )
    {
      constexpr int stride = nDim == 2 ? 2 : 3;
      if ( nPoints < 1 )
        throw std::invalid_argument( MakeString() << __PRETTY_FUNCTION__ << ": a section needs points" );
      fibers.clear();
      double area = 0, yc = 0, zc = 0;
      for ( int i = 0; i < nPoints; i++ ) {
        const double* p = points + i * stride;
        Fiber         f{ p[0], nDim == 2 ? 0.0 : p[1], p[stride - 1], FiberS::Zero(), nullptr };
        if ( f.area <= 0 )
          throw std::invalid_argument( MakeString()
                                       << __PRETTY_FUNCTION__ << ": section point " << i << " has no positive area" );
        area += f.area;
        yc += f.y * f.area;
        zc += f.z * f.area;
        fibers.push_back( std::move( f ) );
      }
      yc /= area;
      zc /= area;

      double polar = 0;
      for ( const auto& f : fibers )
        polar += ( ( f.y - yc ) * ( f.y - yc ) + ( f.z - zc ) * ( f.z - zc ) ) * f.area;
      if ( nDim == 3 && ( J <= 0 || polar <= 0 ) )
        throw std::invalid_argument( MakeString() << __PRETTY_FUNCTION__
                                                  << ": a 3D section needs a positive torsion constant and points "
                                                     "spread over the section" );
      torsionScaling = nDim == 2 ? 0.0 : std::sqrt( J / polar );

      for ( auto& f : fibers ) {
        if constexpr ( nDim == 2 )
          f.S << 1, -f.y, //
            0, 0,         //
            0, 0;
        else
          f.S << 1, f.z, -f.y, 0,                    //
            0, 0, 0, -torsionScaling * ( f.z - zc ), //
            0, 0, 0, torsionScaling * ( f.y - yc );
      }
    }

    /// the section constants of the points: A, the first moments int y dA, int z dA, Iy = int z^2 dA, Iz = int y^2
    /// dA, Iyz = int y z dA (w.r.t. the beam axis)
    std::array< double, 6 > integrals() const
    {
      std::array< double, 6 > c{};
      for ( const auto& f : fibers ) {
        c[0] += f.area;
        c[1] += f.y * f.area;
        c[2] += f.z * f.area;
        c[3] += f.z * f.z * f.area;
        c[4] += f.y * f.y * f.area;
        c[5] += f.y * f.z * f.area;
      }
      return c;
    }

    /// one material instance per fiber, created by name through the factory
    void createMaterials( const std::string& name,
                          const double*      properties,
                          int                nProperties,
                          int                elLabel,
                          double             characteristicLength )
    {
      for ( auto& f : fibers ) {
        f.material = std::unique_ptr< MarmotMaterialHypoElastic >(
          MarmotLibrary::MarmotMaterialHypoElasticFactory::createMaterial( name, properties, nProperties, elLabel ) );
        f.material->setCharacteristicElementLength( characteristicLength );
      }
    }

    bool hasMaterials() const { return !fibers.empty() && fibers[0].material; }

    int nMaterialStateVars() const { return hasMaterials() ? fibers[0].material->getNumberOfRequiredStateVars() : 0; }

    int nFiberStride() const { return nFiberStateVars + nMaterialStateVars(); }

    int getNumberOfRequiredStateVars() const { return static_cast< int >( fibers.size() ) * nFiberStride(); }

    double* fiberState( double* sectionState, size_t k ) const { return sectionState + k * nFiberStride(); }

    void initializeStateVars( double* sectionState ) const
    {
      for ( size_t k = 0; k < fibers.size(); k++ ) {
        double* fs = fiberState( sectionState, k );
        std::fill( fs, fs + nFiberStateVars, 0.0 );
        fibers[k].material->initializeYourself( fs + nFiberStateVars, nMaterialStateVars() );
      }
    }

    /**
     * Section forces and tangent for the increment of the generalized strains; updates the fiber states.
     * @param energy, dissipation the section's elastic energy and dissipation per length
     */
    void computeSection( double*          sectionState,
                         VectorGen&       s,
                         MatrixGen&       D,
                         double&          energy,
                         double&          dissipation,
                         const VectorGen& dE,
                         double           time,
                         double           dT ) const
    {
      s.setZero();
      D.setZero();
      energy = dissipation = 0;
      for ( size_t k = 0; k < fibers.size(); k++ ) {
        const Fiber&          fiber = fibers[k];
        double*               fs    = fiberState( sectionState, k );
        Eigen::Matrix3d       C     = Eigen::Matrix3d::Zero();
        const Eigen::Vector3d dEps  = fiber.S * dE;

        if constexpr ( nDim == 2 ) {
          MarmotMaterialHypoElastic::state1D state;
          state.stress               = fs[0];
          state.elasticEnergyDensity = fs[3];
          state.dissipation          = fs[4];
          state.stateVars            = fs + nFiberStateVars;
          fiber.material->computeUniaxialStress( state, C( 0, 0 ), dEps( 0 ), { time, dT } );
          fs[0] = state.stress;
          fs[3] = state.elasticEnergyDensity;
          fs[4] = state.dissipation;
        }
        else {
          MarmotMaterialHypoElastic::stateBeam state;
          state.stress               = Eigen::Map< const Eigen::Vector3d >( fs );
          state.elasticEnergyDensity = fs[3];
          state.dissipation          = fs[4];
          state.stateVars            = fs + nFiberStateVars;
          fiber.material->computeBeamStress( state, C, dEps, { time, dT } );
          Eigen::Map< Eigen::Vector3d > sigmaNew( fs );
          sigmaNew = state.stress;
          fs[3]    = state.elasticEnergyDensity;
          fs[4]    = state.dissipation;
        }

        const Eigen::Map< const Eigen::Vector3d > sigma( fs );
        s += fiber.S.transpose() * sigma * fiber.area;
        D += fiber.S.transpose() * C * fiber.S * fiber.area;
        energy += fs[3] * fiber.area;
        dissipation += fs[4] * fiber.area;
      }
    }

    /// the state "stress" ([sigma11, sigma12, sigma13]) or a material state of fiber k
    StateView getFiberStateView( double* sectionState, size_t k, const std::string& name ) const
    {
      if ( k >= fibers.size() )
        throw std::invalid_argument( MakeString() << __PRETTY_FUNCTION__ << ": fiber " << k << " does not exist" );
      double* fs = fiberState( sectionState, k );
      if ( name == "stress" )
        return { fs, 3 };
      return fibers[k].material->getStateView( name, fs + nFiberStateVars );
    }
  };

} // namespace Marmot::Elements
